"""test admins and cms

Revision ID: 524268d36289
Revises: 
Create Date: 2019-04-01 03:17:05.077026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524268d36289'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_administrator_username'), 'administrator', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_administrator_username'), table_name='administrator')
    op.drop_table('administrator')
    # ### end Alembic commands ###
